---
- name: Listen for approved requested items from ServiceNow
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5003

  rules:

    - name: Run the windows daily demo workflow
      condition: event.payload.short_description  == "Faith AAP Windows AWS Daily Demo"
      action:
        run_job_template:
          name: "print snow output"
          organization: "Default"
          job_args:
            extra_vars:
              ticket_number: "{{ event.payload.number }}"
              ticket_sys_id: "{{ event.payload.sys_id }}"

    - name: Run the linux daily demo workflow
      condition: event.payload.short_description  == "Ames AAP Linux AWS Daily Demo"
      action:
        run_workflow_template:
          name: "Run workflow for the Linux Daily Demo"
          organization: "Default"
          job_args:
            extra_vars:
              ticket_number: "{{ event.payload.number }}"
              ticket_sys_id: "{{ event.payload.sys_id }}"

    - name: Run the automated patching workflow
      condition: event.payload.short_description  == "Control01 Ansible Automation Platform (AAP) automated vulnerability remediation"
      action:
        run_job_template:
          name: "print snow output"
          organization: "Default"
          job_args:
            extra_vars:
              ticket_number: "{{ event.payload.number }}"
              ticket_sys_id: "{{ event.payload.sys_id }}"
